apiVersion: v1
kind: Service
metadata:
  name: innovatech-frontend-service
  namespace: innovatech
  annotations:
    # Indicamos que el LB lo maneja el AWS Load Balancer Controller
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    # Forzamos que sea público y (no interno)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: innovatech-frontend    # Debe coincidir exactamente con el Deployment
  ports:
    - port: 80
      targetPort: 80